#Github Action yml 파일
name: juhee-study-web01

on:
  push:
    branches:
      - master  # 트리거 브랜치 지정. master로 지정했기 때문에 master에 푸쉬되면 빌드가 시작됨.
    workflow_dispatch:  # 브랜치 push 이벤트 외, 수동으로 실행하도록 설정할 수 있음

jobs:
  build:
    runs-on: ubuntu-latest   # 해당 Github Action 스크립트가 작동될 OS환경 지정 - Centos가 공식지원하지 않아 Ubuntu 사용한다고 함(202104)

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # 프로젝트코드를 checkout한다

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  # Github Action이 실행될 OS에 JAVA를 설치한다
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # gradle wrapper 실행 권한 부여(+x) - 이 권한을 줘야 다음 스크립트를 진행할 수 있음
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build  # gradle wrapper를 통해 해당 프로젝트를 build 한다
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2  # 1466587594/get-current-time 액션은 Moment.js를 사용한다고함! 그래서 포맷도 동일하게 사용 가능
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"  # 한국시간에 맞추기 위해 +9시간 함

      - name: Show Current Time
        run: echo "CurrentTiem=${{steps.current-time.outputs.formattedTime}}"  # Get current time에서 지정한 포맷대로 현재 시간을 표출한다
        shell: bash

      - name: Generate deployment package  # Gradle Build를 통해 만들어진 jar파일을 Beanstalk에 배포하기위한 zip파일로 만들어줄 스크립트
        run:
          mkdir -p deploy
        cp build/libs/*.jar deploy/application.jar  # 빌드가 끝나면 해당 배포 jar파일의 파일명을 application.jar로 교체함(이유=매 빌드마다 파일명이 달라지는데 찾기 쉬우려고)
        cp Procfile deploy/Procfile
        cp -r .ebextentions deploy/.ebextensions
        cp -r .platform deploy/.platform
        cd deploy && zip -r deploy.zip .  # 3개 파일or디렉터리을 함께 zip에 포함시킨다(Procfile, .ebextensions, .platform)

      - name: Deploy to EB  # Beanstalk 플러그인 사용하기
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: study-web01
          environment_name: study-web01
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}  # 현재시간을 이용해서 Beanstalk가 배포할 때마다 유니크한 버저닝이 될 수 있도록
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
